Adjusting nginx config to match new static file layout

diff --git a/build b/build
--- a/build
+++ b/build
@@ -43,9 +43,9 @@ sudo docker exec "${container_id}" \
   env TERM=xterm \
   ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml \
   | tee "${idempotence_file}"
-grep -q 'changed=0.*failed=0' "${idempotence_file}" && \
-  (echo 'Idempotence test: pass' && exit 0) || \
-  (echo 'Idempotence test: fail' && exit 1)
+grep -q "changed=0.*failed=0" "${idempotence_file}" && \
+  (echo "Idempotence test: pass" && exit 0) || \
+  (echo "Idempotence test: fail" && exit 1)
 
 # Get container's IP address.
 print_ip_python=$(echo "import sys, json;
@@ -54,11 +54,27 @@ container_ip=$(sudo docker inspect "${container_id}" | \
     python -c "${print_ip_python}")
 echo "Container IP Address:" "${container_ip}"
 
-# Check that GreenPiThumb is serving.
-curl -s "${container_ip}"  \
+# Check that GreenPiThumb Frontend is serving.
+curl -s "http://${container_ip}/"  \
   | grep "GreenPiThumb" && \
-  (echo 'Landing page test: pass' && exit 0) || \
-  (echo 'Landing page test: fail' && exit 1)
+  (echo "Landing page test: pass" && exit 0) || \
+  (echo "Landing page test: fail" && exit 1)
+
+# Make sure application files are accessible
+curl -s "http://${container_ip}/app/app.js"
+
+# Make sure vendor files are accessible
+curl -s "http://${container_ip}/vendor/bootstrap/bootstrap.min.css"
+
+# Check that GreenPiThumb Frontend returns 404 on non-existent HTML files.
+response_code=$( \
+  curl -s -o /dev/null -w "%{http_code}" \
+  "http://${container_ip}/non-existent-file.html")
+if [ $response_code == "404" ]; then
+  echo "404 test: pass" && exit 0
+else
+  echo "404 test: fail" && exit 1
+fi
 
 # Clean up
 sudo docker stop "${container_id}"
